### ISSUE TITLE
Data does not show when selecting another request

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/debugbar#14]
When you select another request, the data does not show until you select another tab

**Comment by josephmancuso** [comment]
@girardinsamuel if you can take a look at this i think it has to do with the reactivity of the Alpine object

**Comment by girardinsamuel** [comment]
Actually now data is displayed.
The reactivity issue is content loading from the current tab.
Actually message count is correctly updated for each collector.
If you go to next tab and then go back, here the data will be updated..

Same issue that: at first load the content is not displayed we need to switch to another tab and go back to the tab
