### ISSUE TITLE
Need to store package assets inside package and load them in

### ISSUE THREAD

**Issue by josephmancuso** [MasoniteFramework/debugbar#21]
we need to be able to use this package offline. A lot of development is all done locally so we need to store any assets we use in the package and load them in.

We can't use a CDN all the time. We should store these assets in the package and then when we render we can just load the javascript minified asset into the javascript renderer.. if that makes sense.

**Comment by girardinsamuel** [comment]
Yes absolutely.
But that's not that easy

**Comment by josephmancuso** [comment]
done
